# Generated by Django 4.2.1 on 2023-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("news_index", models.BigAutoField(primary_key=True, serialize=False)),
                ("news_name", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "news_content",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("news_href", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "db_table": "news",
                "managed": False,
            },
        ),
    ]
